🚸 Update to SBB 1.6.1

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -27,6 +27,9 @@ install_packages() {
 	superbbootstrap_install_packages "$DOTFILES_PATH/packageslist"
 
 	printf '\n\033[1;7;34m%s\033[0m\n' 'Install extra packages'
+		# Download submodules
+		git submodule update --init --recursive
+
 		# Python packages
 		pip install --upgrade 'auto-editor' 'git+https://github.com/will8211/unimatrix.git'
 
@@ -46,21 +49,11 @@ install_packages() {
 		done
 
 		# Resource
-			# Textarts and Fetchutils
-			git clone 'https://github.com/NNBnh/textart-collections.git' "$XDG_DATA_HOME/textarts"
-			git clone 'https://github.com/lptstr/fetchutils.git'         "$XDG_DATA_HOME/fetchutils"
-
-			# Figlet fonts
-			git clone 'https://github.com/xero/figlet-fonts.git' "$XDG_DATA_HOME/figlet/fonts"
-
 			# Mono fonts
 			aria2c --dir "$TMPDIR" $(curl --silent --location 'https://api.github.com/repos/NNBnh/bmono/releases/latest' | grep -e '/bmono-ttf.zip' | cut -f '4' -d '"') \
 			&& 7z x -o"$TMPDIR/" "$TMPDIR/bmono-ttf.zip" \
 			&& mkdir -p "$XDG_DATA_HOME/fonts" \
 			&& mv "$TMPDIR/ttf/"* "$XDG_DATA_HOME/fonts/"
-
-			# Wallpapers
-			git clone 'https://github.com/NNBnh/wallpaper-collections.git' "$XDG_DATA_HOME/wallpapers"
 
 			# Mouse cursor
 			aria2c --dir "$TMPDIR" 'https://github.com/ful1e5/Bibata_Cursor/releases/download/v1.0.3/Bibata-Original-Ice.tar.gz' \
@@ -143,132 +136,248 @@ after_symlink() {
 
 # SBB #########################################################################
 
+# WARNING !!!
+# Don't touch anything from this point to the end of file
+# if you don't know what you are doing.
+
+
 # Values
 WD="$PWD"
 
 TMPDIR="${TMPDIR:-/tmp}"
 TEMPORARY="$TMPDIR/superb-bootstrap"
 
-     APT_MARK='APT';      APT_COMMAND='sudo apt install --assume-yes'
-  Pacman_MARK='PAC';   Pacman_COMMAND='sudo pacman --sync --refresh --noconfirm --needed'
-    XBPS_MARK='XBP';     XBPS_COMMAND='sudo xbps-install --sync --yes'
-     AUR_MARK='AUR';      AUR_COMMAND='paru -Sy --nodiffmenu --save --noconfirm'
- Flatpak_MARK='FLA';  Flatpak_COMMAND='sudo flatpak install'
-    Snap_MARK='SNA';     Snap_COMMAND='sudo snap install'
-Homebrew_MARK='HBR'; Homebrew_COMMAND='brew install'
+if [ -x "$(command -v sudo)" ]; then
+	PERMISSION_COMMAND='sudo'
+elif [ -x "$(command -v doas)" ]; then
+	PERMISSION_COMMAND='doas'
+else
+	printf '\n\033[1;7;31m%s\033[0m\n' "Permission command not found or unsupported"
+	exit 1
+fi
+
+     APT_MARK='APT';      APT_PM='apt'         ;      APT_COMMAND="$PERMISSION_COMMAND $APT_PM install --assume-yes"
+  Mports_MARK='MPT';   Mports_PM='mports'      ;   Mports_COMMAND="$PERMISSION_COMMAND $Mports_PM install"
+ OpenBSD_MARK='OBP';  OpenBSD_PM='pkg_add'     ;  OpenBSD_COMMAND="$PERMISSION_COMMAND $OpenBSD_PM -I"
+  Pacman_MARK='PAC';   Pacman_PM='pacman'      ;   Pacman_COMMAND="$PERMISSION_COMMAND $Pacman_PM --sync --noconfirm --needed"
+ Portage_MARK='PTG';  Portage_PM='emerge'      ;  Portage_COMMAND="$PERMISSION_COMMAND $Portage_PM"
+   PKGIN_MARK='PIN';    PKGIN_PM='pkgin'       ;    PKGIN_COMMAND="$PERMISSION_COMMAND $PKGIN_PM install -y"
+   PKGNG_MARK='PNG';    PKGNG_PM='pkg'         ;    PKGNG_COMMAND="$PERMISSION_COMMAND $PKGNG_PM install -y"
+Slackpkg_MARK='SLK'; Slackpkg_PM='slackpkg'    ; Slackpkg_COMMAND="$PERMISSION_COMMAND $Slackpkg_PM install"
+    XBPS_MARK='XBP';     XBPS_PM='xbps-install';     XBPS_COMMAND="$PERMISSION_COMMAND $XBPS_PM --yes"
+  Zypper_MARK='ZPR';   Zypper_PM='zypper'      ;   Zypper_COMMAND="$PERMISSION_COMMAND $Zypper_PM --non-interactive install"
+     AUR_MARK='AUR';      AUR_PM='paru'        ;      AUR_COMMAND="$AUR_PM --sync --skipreview --useask --noconfirm"
+ Flatpak_MARK='FLA';  Flatpak_PM='flatpak'     ;  Flatpak_COMMAND="$PERMISSION_COMMAND $Flatpak_PM install"
+Homebrew_MARK='HBR'; Homebrew_PM='brew'        ; Homebrew_COMMAND="$Homebrew_PM install"
+     SBO_MARK='SBO';      SBO_PM='sbopkg'      ;      SBO_COMMAND="$PERMISSION_COMMAND $SBO_PM -ifq"
+    Snap_MARK='SNA';     Snap_PM='snap'        ;     Snap_COMMAND="$PERMISSION_COMMAND $Snap_PM install"
+
+case $(uname -s | tr '[:upper:]' '[:lower:]') in
+	'darwin'*)
+		PACKAGEMANAGER_MAIN='Homebrew'
+	;;
+	'freebsd'*)
+		PACKAGEMANAGER_MAIN='PKGNG'
+	;;
+	'midnightbsd'*)
+		PACKAGEMANAGER_MAIN='Mports'
+	;;
+	'netbsd'*)
+		PACKAGEMANAGER_MAIN='PKGIN'
+	;;
+	'openbsd'*)
+		PACKAGEMANAGER_MAIN='OpenBSD'
+	;;
+	*)
+		for packagemanager_check in 'APT' 'Pacman' 'Portage' 'Slackpkg' 'XBPS' 'Zypper'; do
+			[ -x $(eval "command -v \"\$${packagemanager_check}_PM\"") ] && {
+				PACKAGEMANAGER_MAIN="$packagemanager_check"
+				break
+			}
+		done
+
+		[ "$PACKAGEMANAGER_MAIN"  = 'Pacman'   ] && PACKAGEMANAGER_LIST="$PACKAGEMANAGER_LIST AUR"
+		[ "$PACKAGEMANAGER_MAIN"  = 'Slackpkg' ] && PACKAGEMANAGER_LIST="$PACKAGEMANAGER_LIST SBO"
+		                                            PACKAGEMANAGER_LIST="$PACKAGEMANAGER_LIST Flatpak"
+
+		if [ "$PACKAGEMANAGER_MAIN" = 'APT' ] || [ "$PACKAGEMANAGER_MAIN" = 'Pacman' ]; then
+			PACKAGEMANAGER_LIST="$PACKAGEMANAGER_LIST Snap"
+		fi
+	;;
+esac
+
+PACKAGEMANAGER_LIST="$PACKAGEMANAGER_MAIN $PACKAGEMANAGER_LIST" # This is a list of package managers supported on bootstrapping OS
 
 
 # Functions
 superbbootstrap_install_packages() {
 	if [ -f "$1" ]; then
 		packages_list=$(sed -e 's/#.*$//g' "$1")
+	elif [ -z "$PACKAGEMANAGER_MAIN" ]; then
+		printf '\n\033[1;7;31m%s\033[0m\n' "Main packages manager not found or unsupported"
+		exit 1
 	else
 		printf '\n\033[1;7;31m%s\033[0m\n' 'Packages list not found'
 		exit 1
 	fi
 
-	case $(uname -s | sed -e 's/[[:upper:]]/\L&/g') in
-		'darwin'*)
-			packagemanager_main='Homebrew'
-		;;
-		*)
-			  if command -v apt          >/dev/null; then packagemanager_main='APT'
-			elif command -v pacman       >/dev/null; then packagemanager_main='Pacman'
-			elif command -v xbps-install >/dev/null; then packagemanager_main='XBPS'
-			else
-				printf '\n\033[1;7;31m%s\033[0m\n' "Packages manager not found"
-				exit 1
-			fi
-
-			[ "$packagemanager_main"  = 'Pacman' ] && packagemanager_list="$packagemanager_list AUR"
-			                                          packagemanager_list="$packagemanager_list Flatpak"
-			[ "$packagemanager_main" != 'XBPS'   ] && packagemanager_list="$packagemanager_list Snap"
-		;;
-	esac
-
-	packagemanager_list="$packagemanager_main${packagemanager_list:+ $packagemanager_list}"
-
-
-	for packagemanager in $packagemanager_list; do
+	for packagemanager in $PACKAGEMANAGER_LIST; do
 		eval "mark=\"\$${packagemanager}_MARK\""
 		eval "install_command=\"\$${packagemanager}_COMMAND\""
 
+		# Find packages with mark
 		packages_installing=$(printf '%s' "$packages_list" | sed -e "s/^.*$mark://g" -e 's/[[:space:]].*$//g' -e '/^$/d' | tr '\n' ' ')
 
+		# If finded, setup package manager then install packages
 		[ -n "$packages_installing" ] && {
+			# Remove lines with current mark so packages don't get reinstall on another package managers later on
 			packages_list=$(printf '%s' "$packages_list" | sed -e "s/^.*$mark.*\$//g")
 
 			printf '\n\033[1;7;35m%s\033[0m\n' "Setting up $packagemanager"
 			eval "superbbootstrap_$packagemanager"
 
-			printf '\n\033[1;7;32m%s\033[0m\n' "Installing $packagemanager Packages"
+			printf '\n\033[1;7;32m%s\033[0m\n' "Installing $packagemanager packages"
 			eval "$install_command $packages_installing"
 		}
 	done
 }
 
 superbbootstrap_APT() {
-	sudo apt update  --assume-yes
-	sudo apt upgrade --assume-yes
+	$PERMISSION_COMMAND apt update  --assume-yes
+	$PERMISSION_COMMAND apt upgrade --assume-yes
+}
+
+superbbootstrap_Mports() {
+	$PERMISSION_COMMAND mport index
+	$PERMISSION_COMMAND mport upgrade
+}
+
+superbbootstrap_OpenBSD() {
+	$PERMISSION_COMMAND syspatch
 }
 
 superbbootstrap_Pacman() {
-	sudo pacman --sync --sysupgrade --refresh --noconfirm --needed
+	$PERMISSION_COMMAND pacman --sync --sysupgrade --refresh --noconfirm --needed
+}
+
+superbbootstrap_Portage() {
+	$PERMISSION_COMMAND emerge --sync
+	$PERMISSION_COMMAND emerge --update --newuse --deep --with-bdeps=y @world
+}
+
+superbbootstrap_PKGIN() {
+	$PERMISSION_COMMAND pkgin update -y
+	$PERMISSION_COMMAND pkgin upgrade -y
+}
+
+superbbootstrap_PKGNG() {
+	$PERMISSION_COMMAND pkg update -y
+	$PERMISSION_COMMAND pkg upgrade -y
+}
+
+superbbootstrap_Slackpkg() {
+	$PERMISSION_COMMAND slackpkg update gpg
+	$PERMISSION_COMMAND slackpkg update
 }
 
 superbbootstrap_XBPS() {
-	sudo xbps-install --sync --yes --update
-	sudo xbps-install --sync --yes --update
-	sudo xbps-install --sync --yes void-repo-nonfree void-repo-multilib void-repo-multilib-nonfree void-repo-debug
+	$PERMISSION_COMMAND xbps-install --sync --yes --update # Update XBPS itself so it can update other packages
+	$PERMISSION_COMMAND xbps-install --sync --yes --update # Update packages
+	$PERMISSION_COMMAND xbps-install --sync --yes void-repo-nonfree void-repo-multilib void-repo-multilib-nonfree void-repo-debug
+}
+
+superbbootstrap_Zypper() {
+	$PERMISSION_COMMAND zypper --non-interactive update
 }
 
 superbbootstrap_AUR() {
-	sudo pacman --sync --refresh --noconfirm --needed git base-devel
-	git clone 'https://aur.archlinux.org/paru.git' "$TEMPORARY/paru"
-	cd "$TEMPORARY/paru" || exit 1
-	makepkg -si
-	cd "$WD" || exit 1
+	if [ ! -x "$(command -v 'paru')" ]; then
+		$Pacman_COMMAND git base-devel
+		git clone 'https://aur.archlinux.org/paru.git' "$TEMPORARY/paru"
+		cd "$TEMPORARY/paru" || exit 1
+		makepkg -si
+		cd "$WD" || exit 1
+	else
+		printf '%s\n' "Paru has been installed"
+	fi
 }
 
 superbbootstrap_Flatpak() {
-	case "$packagemanager_main" in
-	'Pacman') sudo pacman --sync --refresh --noconfirm --needed flatpak           ;;
-	'APT')    sudo apt install --assume-yes flatpak gnome-software-plugin-flatpak ;;
-	'XBPS')   sudo xbps-install --sync --yes flatpak                              ;;
-	esac
+	if [ ! -x "$(command -v 'flatpak')" ]; then
+		case "$PACKAGEMANAGER_MAIN" in
+			'APT')         $APT_COMMAND flatpak gnome-software-plugin-flatpak ;;
+			'Portage') $Portage_COMMAND sys-apps/flatpak                      ;;
+			'Pacman')   $Pacman_COMMAND flatpak                               ;;
+			'XBPS')       $XBPS_COMMAND flatpak                               ;;
+			'Zypper')   $Zypper_COMMAND flatpak                               ;;
+			'Slackpkg')
+				if [ ! -x "$(command -v "$SBO_PM")" ]; then
+					superbbootstrap_SBO
+				fi
+
+				$SBO_COMMAND flatpak
+			;;
+		esac
+	else
+		printf '%s\n' "Flatpak has been installed"
+	fi
 
 	flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
 }
 
-superbbootstrap_Snap() {
-	if [ $packagemanager_main = 'Pacman' ]; then
-		sudo pacman --sync --refresh --noconfirm --needed git
-		git clone 'https://aur.archlinux.org/snapd.git' "$TEMPORARY/snap"
-		cd "$TEMPORARY/snap" || exit 1
-		makepkg -si
+superbbootstrap_Homebrew() {
+	if [ ! -x "$(command -v 'brew')" ] >/dev/null; then
+		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+	else
+		printf '%s\n' "Homebrew has been installed"
+	fi
+}
+
+superbbootstrap_SBO() {
+	if [ ! -x "$(command -v 'sbopkg')" ]; then
+		SLACKWARE_VERSION=$(cut -f '2' -d ' ' '/etc/slackware-version')
+		SBO_VERSION=$(curl -s "https://api.github.com/repos/sbopkg/sbopkg/releases/latest" | grep -e 'tag_name' | cut -f '4' -d '"')
+		cd "$TEMPORARY" || exit 1
+		curl --remote-header-name --location --remote-name "https://github.com/sbopkg/sbopkg/releases/download/$SBO_VERSION/sbopkg-$SBO_VERSION-noarch-1_wsr.tgz"
+		upgradepkg --install-new "$TEMPORARY/sbopkg-$SBO_VERSION-noarch-1_wsr.tgz"
 		cd "$WD" || exit 1
-		sudo systemctl enable --now snapd.socket
-		sudo ln -s '/var/lib/snapd/snap' '/snap'
-	elif [ $packagemanager_main = 'APT' ]; then
-		sudo apt install --assume-yes snapd
+		$PERMISSION_COMMAND mkdir -p "/var/lib/sbopkg/SBo/$SLACKWARE_VERSION" "/var/lib/sbopkg/queues" "/var/log/sbopkg" "/var/cache/sbopkg"
+		$PERMISSION_COMMAND sbopkg -rq
+		$PERMISSION_COMMAND sqg -a
+	else
+		printf '%s\n' "Sbopkg has been installed"
+	fi
+}
+
+superbbootstrap_Snap() {
+	if [ ! -x "$(command -v 'snap')" ]; then
+		if [ $PACKAGEMANAGER_MAIN = 'Pacman' ]; then
+			$PERMISSION_COMMAND pacman --sync --noconfirm --needed git
+			git clone 'https://aur.archlinux.org/snapd.git' "$TEMPORARY/snap"
+			cd "$TEMPORARY/snap" || exit 1
+			makepkg -si
+			cd "$WD" || exit 1
+			$PERMISSION_COMMAND systemctl enable --now snapd.socket
+			$PERMISSION_COMMAND ln -s '/var/lib/snapd/snap' '/snap'
+		elif [ $PACKAGEMANAGER_MAIN = 'APT' ]; then
+			$APT_COMMAND snapd
+		fi
+	else
+		printf '%s\n' "Snapd has been installed"
 	fi
 
 	snap install core
-}
-
-superbbootstrap_Homebrew() {
-	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
 }
 
 
 # Start
 for step_check in $STEPS; do
 	case "$step_check" in
-		'i'|'install') steps_list="${steps_list:+$steps_list }install_packages;" ;;
-		'b'|'before')  steps_list="${steps_list:+$steps_list }before_symlink;"   ;;
-		'h'|'home')    steps_list="${steps_list:+$steps_list }symlink_home;"     ;;
-		'r'|'root')    steps_list="${steps_list:+$steps_list }symlink_root;"     ;;
-		'a'|'after')   steps_list="${steps_list:+$steps_list }after_symlink;"    ;;
+		'i'|'install') steps_list="${steps_list:+$steps_list; }install_packages" ;;
+		'b'|'before')  steps_list="${steps_list:+$steps_list; }before_symlink"   ;;
+		'h'|'home')    steps_list="${steps_list:+$steps_list; }symlink_home"     ;;
+		'r'|'root')    steps_list="${steps_list:+$steps_list; }symlink_root"     ;;
+		'a'|'after')   steps_list="${steps_list:+$steps_list; }after_symlink"    ;;
 		*)
 			printf '\n\033[1;7;31m%s\033[0m\n' "Step '$step_check' not found"
 			exit 1
