🚸 Update to SBB 1.7.3

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -43,15 +43,6 @@ install_packages() {
 			basher install "$basher_package"
 		done
 
-		# Git alias
-		curl -fsSL 'https://raw.githubusercontent.com/GitAlias/gitalias/master/gitalias.txt' --create-dirs --output "$XDG_DATA_HOME/git/gitalias.txt"
-
-		# MPV
-		mkdir -p "$XDG_CONFIG_HOME/mpv/scripts" \
-		&& for mpv_script in 'detect-image.lua' 'freeze-window.lua' 'image-positioning.lua' 'ruler.lua'; do
-			curl -fsSL "https://raw.githubusercontent.com/occivink/mpv-image-viewer/master/scripts/$mpv_script" > "$XDG_CONFIG_HOME/mpv/scripts/$mpv_script"
-		done
-
 		# Resource
 			# Mono fonts
 			aria2c --dir "$TMPDIR" $(curl --silent --location 'https://api.github.com/repos/NNBnh/bmono/releases/latest' | grep -e '/bmono-ttf.zip' | cut -f '4' -d '"') \
@@ -152,6 +143,17 @@ TEMPORARY="$TMPDIR/superb-bootstrap"
 
 DOTFILES_PATH=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
 
+if [ -x "$(command -v sudo)" ]; then
+	PERMISSION_COMMAND='sudo'
+elif [ -x "$(command -v doas)" ]; then
+	PERMISSION_COMMAND='doas'
+elif [ -x "$(command -v termux-setup-storage)" ]; then
+	PACKAGEMANAGER_MAIN='Termux'
+else
+	printf '\n\033[1;7;31m%s\033[0m\n' "Permission command not found or unsupported"
+	exit 1
+fi
+
      APT_MARK='APT';      APT_PM='apt'         ;      APT_COMMAND="$PERMISSION_COMMAND $APT_PM install --assume-yes"
   Mports_MARK='MPT';   Mports_PM='mports'      ;   Mports_COMMAND="$PERMISSION_COMMAND $Mports_PM install"
  OpenBSD_MARK='OBP';  OpenBSD_PM='pkg_add'     ;  OpenBSD_COMMAND="$PERMISSION_COMMAND $OpenBSD_PM -I"
@@ -163,7 +165,7 @@ Slackpkg_MARK='SLK'; Slackpkg_PM='slackpkg'    ; Slackpkg_COMMAND="$PERMISSION_C
   Termux_MARK='TMP';   Termux_PM='pkg'         ;   Termux_COMMAND="$Termux_PM install --assume-yes"
     XBPS_MARK='XBP';     XBPS_PM='xbps-install';     XBPS_COMMAND="$PERMISSION_COMMAND $XBPS_PM --yes"
   Zypper_MARK='ZPR';   Zypper_PM='zypper'      ;   Zypper_COMMAND="$PERMISSION_COMMAND $Zypper_PM --non-interactive install"
-     AUR_MARK='AUR';      AUR_PM='paru'        ;      AUR_COMMAND="$AUR_PM --sync --skipreview --useask --noconfirm"
+     AUR_MARK='AUR';      AUR_PM='paru'        ;      AUR_COMMAND="$AUR_PM --sync --skipreview --useask --noconfirm --needed"
  Flatpak_MARK='FLA';  Flatpak_PM='flatpak'     ;  Flatpak_COMMAND="$PERMISSION_COMMAND $Flatpak_PM install"
 Homebrew_MARK='HBR'; Homebrew_PM='brew'        ; Homebrew_COMMAND="$Homebrew_PM install"
 MacPorts_MARK='MCP'; MacPorts_PM='port'        ; MacPorts_COMMAND="$PERMISSION_COMMAND $MacPorts_PM install"
@@ -171,54 +173,45 @@ MacPorts_MARK='MCP'; MacPorts_PM='port'        ; MacPorts_COMMAND="$PERMISSION_C
      SBO_MARK='SBO';      SBO_PM='sbopkg'      ;      SBO_COMMAND="$PERMISSION_COMMAND $SBO_PM -ifq"
     Snap_MARK='SNA';     Snap_PM='snap'        ;     Snap_COMMAND="$PERMISSION_COMMAND $Snap_PM install"
 
-case $(uname -s | tr '[:upper:]' '[:lower:]') in
-	'darwin'*)
-		PACKAGEMANAGER_LIST='Homebrew MacPorts MAS'
-	;;
-	'freebsd'*)
-		PACKAGEMANAGER_MAIN='PKGNG'
-	;;
-	'midnightbsd'*)
-		PACKAGEMANAGER_MAIN='Mports'
-	;;
-	'netbsd'*)
-		PACKAGEMANAGER_MAIN='PKGIN'
-	;;
-	'openbsd'*)
-		PACKAGEMANAGER_MAIN='OpenBSD'
-	;;
-	*)
-		for packagemanager_check in 'Termux' 'APT' 'Pacman' 'Portage' 'Slackpkg' 'XBPS' 'Zypper'; do
-			[ -x $(eval "command -v \"\$${packagemanager_check}_PM\"") ] && {
-				PACKAGEMANAGER_MAIN="$packagemanager_check"
-				break
-			}
-		done
+if [ -z "$PACKAGEMANAGER_MAIN" ]; then
+	case $(uname -s | tr '[:upper:]' '[:lower:]') in
+		'darwin'*)
+			PACKAGEMANAGER_LIST='Homebrew MacPorts MAS'
+		;;
+		'freebsd'*)
+			PACKAGEMANAGER_MAIN='PKGNG'
+		;;
+		'midnightbsd'*)
+			PACKAGEMANAGER_MAIN='Mports'
+		;;
+		'netbsd'*)
+			PACKAGEMANAGER_MAIN='PKGIN'
+		;;
+		'openbsd'*)
+			PACKAGEMANAGER_MAIN='OpenBSD'
+		;;
+		*)
 
-		[ "$PACKAGEMANAGER_MAIN" != 'Termux' ] && {
+			for packagemanager_check in 'APT' 'Pacman' 'Portage' 'Slackpkg' 'XBPS' 'Zypper'; do
+				[ -x "$(eval command -v \$${packagemanager_check}_PM)" ] && {
+					PACKAGEMANAGER_MAIN="$packagemanager_check"
+					break
+				}
+			done
+
 			[ "$PACKAGEMANAGER_MAIN"  = 'Pacman'   ] && PACKAGEMANAGER_LIST="$PACKAGEMANAGER_LIST AUR"
 			[ "$PACKAGEMANAGER_MAIN"  = 'Slackpkg' ] && PACKAGEMANAGER_LIST="$PACKAGEMANAGER_LIST SBO"
 			                                            PACKAGEMANAGER_LIST="$PACKAGEMANAGER_LIST Flatpak"
 			                                            PACKAGEMANAGER_LIST="$PACKAGEMANAGER_LIST Homebrew"
-		}
 
-		if [ "$PACKAGEMANAGER_MAIN" = 'APT' ] || [ "$PACKAGEMANAGER_MAIN" = 'Pacman' ]; then
-			PACKAGEMANAGER_LIST="$PACKAGEMANAGER_LIST Snap"
-		fi
-	;;
-esac
-
-PACKAGEMANAGER_LIST="$PACKAGEMANAGER_MAIN $PACKAGEMANAGER_LIST" # This is a list of package managers supported on bootstrapping OS
-
-if [ -x "$(command -v sudo)" ]; then
-	PERMISSION_COMMAND='sudo'
-elif [ -x "$(command -v doas)" ]; then
-	PERMISSION_COMMAND='doas'
-elif [ "$PACKAGEMANAGER_MAIN" != 'Termux' ]; then
-	printf '\n\033[1;7;31m%s\033[0m\n' "Permission command not found or unsupported"
-	exit 1
+			if [ "$PACKAGEMANAGER_MAIN" = 'APT' ] || [ "$PACKAGEMANAGER_MAIN" = 'Pacman' ]; then
+				PACKAGEMANAGER_LIST="$PACKAGEMANAGER_LIST Snap"
+			fi
+		;;
+	esac
 fi
 
+PACKAGEMANAGER_LIST="$PACKAGEMANAGER_MAIN $PACKAGEMANAGER_LIST" # This is a list of package managers supported on bootstrapping OS
 
 # Functions
 superbbootstrap_install_packages() {
@@ -237,7 +230,7 @@ superbbootstrap_install_packages() {
 		eval "install_command=\"\$${packagemanager}_COMMAND\""
 
 		# Find packages with mark
-		packages_installing=$(printf '%s' "$packages_list" | sed -e "s/^.*$mark://g" -e 's/[[:space:]].*$//g' -e '/^$/d' | tr '\n' ' ')
+		packages_installing=$(printf '%s' "$packages_list" | sed -e "/^.*$mark:.*\$/!d;s/.*$mark://g" -e 's/[[:space:]].*$//g;/^$/d' | tr '\n' ' ')
 
 		# If finded, setup package manager then install packages
 		[ -n "$packages_installing" ] && {
@@ -268,7 +261,7 @@ superbbootstrap_OpenBSD() {
 }
 
 superbbootstrap_Pacman() {
-	$PERMISSION_COMMAND pacman --sync --sysupgrade --refresh --noconfirm --needed
+	yes | LC_ALL=en_US.UTF-8 $PERMISSION_COMMAND pacman --sync --sysupgrade --refresh --needed
 }
 
 superbbootstrap_Portage() {
@@ -311,10 +304,12 @@ superbbootstrap_AUR() {
 		$Pacman_COMMAND git base-devel
 		git clone 'https://aur.archlinux.org/paru.git' "$TEMPORARY/paru"
 		cd "$TEMPORARY/paru" || exit 1
-		makepkg -si
+		makepkg --syncdeps --noconfirm
+		$PERMISSION_COMMAND $Pacman_PM --needed --noconfirm --upgrade paru-*.zst 
 		cd "$WD" || exit 1
 	else
 		printf '%s\n' "Paru has been installed"
+		$AUR_COMMAND --sysupgrade --refresh --aur
 	fi
 }
 
@@ -414,6 +409,48 @@ superbbootstrap_Snap() {
 	fi
 
 	snap install core
+}
+
+superbbootstrap_batch_symlink() {
+	batch_symlink_directory="$1"
+	batch_symlink_target="$2"
+	batch_symlink_permission="$3"
+
+	[ -n "$TRASH_PATH" ] && mkdir -p "$TRASH_PATH"
+
+	if [ -d "$1" ]; then
+		superbbootstrap_scan_directory "$batch_symlink_directory"
+	else
+		printf '\n\033[1;7;31m%s\033[0m\n' "'$batch_symlink_directory' not found"
+	fi
+}
+
+superbbootstrap_scan_directory() {
+	[ -d "$1" ] || exit 1
+
+	for file in "$1"/.* "$1"/*; do
+		[ "$file" = "$1/." ] || [ "$file" = "$1/.." ] || [ "$file" = "$1/*" ] && continue
+
+		target="$batch_symlink_target${file#$batch_symlink_directory}"
+
+		if [ -e "$target" ]; then
+			if [ -d "$target" ] && [ ! -h "$target" ]; then
+				superbbootstrap_scan_directory "$file"
+			else
+				# You can change how batch symlink handle conflict files
+				if [ -n "$TRASH_PATH" ]; then
+					rm -rf "$TRASH_PATH/$(basename "$target")" 2>&-
+					$batch_symlink_permission mv -f "$target" "$TRASH_PATH/"
+				else
+					$batch_symlink_permission rm -rf "$target"
+				fi
+
+				$batch_symlink_permission ln -sf "$file" "$target"
+			fi
+		else
+			$batch_symlink_permission ln -sf "$file" "$target"
+		fi
+	done
 }
 
 
